import type { Metadata } from "next";
import { Raleway, Poppins } from "next/font/google";
import "./globals.css";

const raleway = Raleway({
	subsets: ["latin"],
	weight: ["400", "600", "700"],
	variable: "--font-heading",
	display: "swap",
});

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600"],
	variable: "--font-body",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${raleway.variable} ${poppins.variable}`}>
			<body className="font-body bg-background text-body">
				{children}
			</body>
		</html>
	);
}
